version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
